spring:
  application:
    name: deploy-lab
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/deploylab}
    username: ${DB_USERNAME:deploylab}
    password: ${DB_PASSWORD:deploylab}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
      group:
        readiness:
          include: readinessState,db

server:
  shutdown: graceful
